### ISSUE TITLE
Missing part of the code: Chapter02/ExploringConsole

### ISSUE THREAD

**Issue by ghost** [markjprice/cs9dotnet5#10]
The tittle "Exploring console applications further" (Fsharp) does not contains a folder on the github repo.

**Comment by markjprice** [comment]
On page 64, I discuss how console apps can have arguments passed to them and I show the following command with arguments as an example:

dotnet new console -lang "F#" --name "ExploringConsole"

The code generated by this command does not need to be in the repo.
