### ISSUE TITLE
Page 391

### ISSUE THREAD

**Issue by pudrik** [markjprice/cs9dotnet5#11]
Not sure if the problem is a subtile security update in EF Core as ive tried it using both the code on the git/book and latest EF Core also.

The Example on page 391 will return 0 rows as the expression $"%{input}%" is used, this issue is due to Escaping but can easily be corrected with $@"%{input}%"

**Comment by markjprice** [comment]
Can you provide more information about your system like OS, version, and so on. The fifth edition was tested with Visual Studio Code on Windows and macOS and it worked fine. I have just tested the code for the sixth edition that uses .NET 6 Preview 4 and Visual Studio 2019 and it still works without adding an @, as shown in the following screenshot:

![queryingwithlike](https://user-images.githubusercontent.com/14040265/120062563-cdf66a00-c05a-11eb-9736-0280b79cf723.png)

**Comment by pudrik** [comment]
Tried on OSX 11.3.1 with VSCode 1.56.2, dotnet 5.0.203 oddly enough i cant cause the bug to reproduce today so its probably a local cache issue in that case, sorry. 

Btw on page 241 there seem to be a platform typo as it states console application for Windows 10 but the syntax however is for OSX.

Also im not sure you mention this anywhere in the book but in order to utilize the builtin terminal for interaction (if you use the Run menu) during debugging and breakpoints (in vscode) you need to alter the launch.json and change the "console" to "integratedTerminal" as omnisharp defaults this to "internalConsole". These issues are however not an issue if you execute the command manually within the terminal.

**Comment by markjprice** [comment]
No worries. I would much rather hear about potential problems than not, so please do keep raising issues if you have them. :)

RE: page 241, good catch. I have added it to the errata and will fix that in the sixth edition: https://github.com/markjprice/cs9dotnet5/blob/master/errata.md#page-241---publishing-a-single-file-app

I don't mention how to utilize the builtin terminal for interaction during debugging but that's a good idea so I will add that to the next edition. Thanks!
