### ISSUE TITLE
Page 505 small syntax inconsistency.

### ISSUE THREAD

**Issue by pudrik** [markjprice/cs9dotnet5#12]
Thru out the book the syntax for writing substructures are mentioned in the convention
Whatever
{
some stuff
}

on 505 however this is broken as it uses 
Supplier = new[] {
stuff..
}

not a critical issue but for consistency you might want to adjust this.

**Comment by markjprice** [comment]
Thanks for the feedback. :)
I would not say it is broken since the code compiles. It is not consistently formatted though since it uses a JavaScript style rather than a C# style for the curly braces. I will fix this in the sixth edition.
