### ISSUE TITLE
Suggestion for improvement regarding csproj files.

### ISSUE THREAD

**Issue by pudrik** [markjprice/cs9dotnet5#13]
Many chapters of the book point out how to manually alter the csproj file to add references to packages or other projects.
However its never mentioned that you can utilize dotnet command lite to add these, and by doing so skipping the dotnet build step as the package is downloaded with the add package argument.

example
For Package references "dotnet add package Microsoft.EntitityFrameworkCore" 
For Project reference "dotnet add reference ../NorthwindContextLib/NorthwindContextLib.csproj"

**Comment by markjprice** [comment]
Hi @pudrik, thank you for your feedback. The first time a project needs NuGet packages, on page 132, I show how to add them using the dotnet add package command. From then on, I assume a reader knows they can do it using the dotnet tool or manually. In the sixth edition, I show how to use (1) dotnet add package and dotnet add reference, and (2) the Visual Studio GUI, and from then on just tell the reader to add package and project references however they like, and just show the resulting project file so they can confirm it worked.
