### ISSUE TITLE
sqlite studio Could not add database with Northwind.db

### ISSUE THREAD

**Issue by ahmednreldin** [markjprice/cs9dotnet5#14]
# Issue Description
@markjprice 
**i'm beginner with sqllite , i follow the steps in the book ( ch11 - Working with EF )
when i try to init sqllite database it gave me this error** 

![image](https://user-images.githubusercontent.com/44178039/120684701-4ddb6480-c49f-11eb-8aa0-2fb475ca0110.png)

**and when i tried to opened the database with Sqlite studio** 
![image](https://user-images.githubusercontent.com/44178039/120684768-621f6180-c49f-11eb-9041-eb95fbcb868a.png)

# Steps i Follow 
**the problem i notice when i opened the database file with notepad ++ i't look like this**

![image](https://user-images.githubusercontent.com/44178039/120684987-a14db280-c49f-11eb-91ea-4eaf5a221c2b.png)

**i try to copy the statement from github to be like this**

![image](https://user-images.githubusercontent.com/44178039/120685032-b0346500-c49f-11eb-901d-272fa7e03993.png)

# finally 

same error still appear

**Comment by markjprice** [comment]
The command at the bottom of page 365 that you need to type is:

sqlite3 Northwind.db -init Northwind.sql

You entered:

sqlite3 Northwind.sql -init Northwind.sql
