### ISSUE TITLE
Invalid link on page 222

### ISSUE THREAD

**Issue by tolache** [markjprice/cs9dotnet5#17]
https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/features-delegates-and-lambda-expressions
this gives 404

**Comment by simonjh77** [comment]
It should be this
https://docs.microsoft.com/en-us/dotnet/csharp/tour-of-csharp/features#delegates-and-lambda-expressions

**Comment by markjprice** [comment]
Thanks, I've added it as an errata and fixed it in the book links file in this repo.
