### ISSUE TITLE
Can not generate Entity classes

### ISSUE THREAD

**Issue by psantos10** [markjprice/cs9dotnet5#2]
Hi @markjprice 

Can you help me with this issue: https://github.com/dotnet/efcore/issues/23660

I run the command, but there are no generated files.

What am I doing wrong? 

Regards

**Comment by markjprice** [comment]
Hi @psantos10, I can see that someone at Microsoft has tried to replicate your issue but it worked fine for them. I have a MacBook Pro but I avoid upgrading the OS for six months after a new release to prevent issues so I am still on macOS Catalina. The ef commands worked for me. I will leave this issue open for now, and once I upgrade to Big Sur next year I will try the tool again.

**Comment by markjprice** [comment]
Hi @psantos10, I have now upgraded to Big Sur and the ef commands work for me. Sorry, but I don't know why they aren't working for you. Did you ever get it working?
