### ISSUE TITLE
.NET Core Launch (console) (Debugging) - Windows 10 not available?

### ISSUE THREAD

**Issue by mORogyrUly** [markjprice/cs9dotnet5#3]
Good evening, 

on my system the option ".NET Core Launch (console Debugging)" is not available , as it is quoted on page 124. 
Never the less it is possible to debug the project with the option ".NET Core Launch (console)".
Is it a configuration "problem" of the system?

The configuration: Windows 10 V20H2, .NET 5 Version 5.0.101, Omnisharp: 1.23.8, VS Code 1.52.1.

**Comment by markjprice** [comment]
Good evening,

The short answer is that it is not a configuration "problem". As you discovered, you were still able to debug.

The long answer is that the list of choices in the dropdown depends on what Visual Studio Code currently has open. Let's review some examples.

If you open any single* folder* as you did, then the list of choices in the dropdown does not need to append the folder name at the end, as shown in the following screenshot:

!(https://user-images.githubusercontent.com/14040265/104507698-11d26080-55df-11eb-883b-fb69a5652bc4.png)

If you open the *Chapter04 workspace* and only the *Debugging* folder has a *.vscode* subfolder with a *launch.json* file, then the dropdown appends the folder name to the end in parentheses, as shown in the following screenshot:

!(https://user-images.githubusercontent.com/14040265/104507729-1b5bc880-55df-11eb-9fa8-a2cd078c8353.png)

If you open the *Chapter04 workspace* and both the *Debugging* folder and the *WritingFunctions* folder have a .*vscode* subfolder with a *launch.json* file, then the dropdown appends the folder names to the end, as shown in the following screenshot:

!(https://user-images.githubusercontent.com/14040265/104507775-2a427b00-55df-11eb-8a3e-675412c067de.png)

**Comment by mORogyrUly** [comment]
Thank you very much for your help. 😀👌
