### ISSUE TITLE
Typo on pages 120-121, chapter 04

### ISSUE THREAD

**Issue by circad200** [markjprice/cs9dotnet5#4]
The Fibonacci sequence at the bottom of page 120 ends with "21 34 65" instead of "21 34 55". This is repeated in the first sentence of the next page where the next term is given as "34 + 65".

**Comment by markjprice** [comment]
Thank you! 

I have added this to the errata: https://github.com/markjprice/cs9dotnet5/blob/master/errata.md#pages-120-and-121---using-lambdas-in-function-implementations
