### ISSUE TITLE
Page 40 - errata

### ISSUE THREAD

**Issue by JebediahW** [markjprice/cs9dotnet5#6]
Don't mean to be pedantic but carriage-return should be replaced with "line terminator".
Especially considering that carriage-return doesn't put the cursor on a new line at all (that's line-feeds job for linux and CR+LF for windows)

**Comment by markjprice** [comment]
Thanks! Pedantic is good when it comes to programming. ;-)

I have fixed this in the sixth edition and in the errata: 
https://github.com/markjprice/cs9dotnet5/blob/master/errata.md#page-40---verbs-are-methods
